### ISSUE TITLE
Check that all text inputs have labels and clicking on labels leads to focus on the field 

### ISSUE THREAD

**Issue by cmac4396** [csiv23/LitCircle#51]
Input labels are located here:

- create club
- leave club for admins
- admin edit bookclub about 
- admin edit bookclub nextMeeting
- admin edit bookclub currentBook (search)
- bookclub members (search) 
- bookclub wishlist + admin wishlist (search)
- bookclub booksRead + admin boooksRead (search)
-  login page
- search books
- search bookclubs 
- edit profile

**Comment by anahiburga** [comment]
https://github.com/csiv23/LitCircle/commit/463f8ca48bd4d5cb0cabb80e5484fa05fe28b83d
